version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Change if you're using a different version of Node.js
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build || echo "Build failed!" && ls -la  # Change if you're using a different build command

  post_build:
    commands:
      - echo Syncing files to S3...
      #- aws s3 sync dist/ s3://testpipeline-bucket --delete  # Change the build directory if needed

      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E1DT61V259KDRE --paths "/*"  # Replace with your actual distribution ID

artifacts:
  files:
    - '**/*'  # Only include files from the dist folder
  base-directory: './dist'
